window.WEDDING_I18N={
  fr:{
    "entry.kicker":"Marrakech · 25—26 mai 2027","entry.open":"OUVRIR L’INVITATION",
    "cover.kicker":"NOUS NOUS MARIONS","cover.place":"Marrakech","cover.date":"25 — 26 mai 2027",
    "photo.kicker":"LE MARIAGE DE","photo.placeholder":"Photo originale à ajouter",
    "countdown.title":"LE COMPTE À REBOURS","countdown.days":"JOURS","countdown.hours":"HEURES","countdown.minutes":"MINUTES","countdown.seconds":"SECONDES",
    "calendar.title":"Mai 2027","calendar.mo":"L","calendar.tu":"M","calendar.we":"M","calendar.th":"J","calendar.fr":"V","calendar.sa":"S","calendar.su":"D","calendar.note":"25 & 26 · Marrakech",
    "venue.kicker":"NOTRE LIEU DE RÉCEPTION","venue.title":"Le lieu","venue.route":"VOIR L’ITINÉRAIRE",
    "program.kicker":"DEUX JOURS · DEUX UNIVERS","program.title":"Programme","program.roots":"RACINES","program.brideHenna":"Henné de la mariée","program.groomHenna":"Henné du marié","program.arrival":"Arrivée des invités","program.families":"Accueil des familles","program.tuaregEvening":"Soirée traditionnelle touarègue","program.dinner":"Dîner","program.music":"Musique / guitare touarègue","program.tea":"Thé & pâtisseries","program.celebration":"LA CÉLÉBRATION","program.ceremony":"Cérémonie","program.cocktail":"Cocktail / accueil","program.seatedDinner":"Dîner à table","program.speeches":"Discours","program.firstDance":"Première danse","program.dj":"DJ & soirée","program.note":"Les horaires non confirmés seront ajoutés dès qu’ils seront fixés.",
    "dress.title":"Dress Code","dress.day1":"Traditionnel / élégant","dress.day2":"Élégant",
    "practical.kicker":"WEDDING DETAILS","practical.title":"Informations pratiques","practical.accommodation":"Hébergement","practical.transport":"Transport","practical.arrival":"Arrivée à Marrakech","practical.passport":"Passeport / visa","practical.weather":"Météo","practical.currency":"Monnaie","practical.mobility":"Déplacements","practical.parking":"Stationnement","practical.children":"Enfants","practical.photos":"Photos","practical.indoorOutdoor":"Cérémonie intérieure / extérieure","practical.pending":"Informations à venir.",
    "travel.kicker":"CARNET DE MARRAKECH","travel.title":"Prolonger le voyage","travel.discover":"À découvrir","travel.restaurants":"Restaurants","travel.cafes":"Cafés","travel.souks":"Souks & artisanat","travel.hammams":"Hammams","travel.excursions":"Excursions","travel.clothing":"Vêtements traditionnels","travel.pending":"Nos adresses sélectionnées seront ajoutées ici.",
    "story.kicker":"QUELQUES LIGNES","story.title":"Notre histoire","story.one":"Deux chemins.","story.two":"Des racines qui voyagent avec nous.","story.three":"Et Marrakech, les 25 & 26 mai 2027.",
    "rsvp.kicker":"CARTE-RÉPONSE","rsvp.question":"Serez-vous des nôtres ?","rsvp.deadline":"Date limite","rsvp.step1":"Votre réponse","rsvp.yes":"Oui, avec joie","rsvp.no":"Non, malheureusement","rsvp.firstName":"Prénom","rsvp.lastName":"Nom","rsvp.step2":"Votre venue","rsvp.companion":"Accompagnant","rsvp.children":"Enfants","rsvp.transport":"Transport souhaité / informations utiles","rsvp.step3":"Repas & préférences","rsvp.allergies":"Allergies","rsvp.diet":"Préférences alimentaires","rsvp.alcohol":"Alcool","rsvp.traditional":"Tenue traditionnelle","rsvp.step4":"Séjour","rsvp.lodging":"Hébergement souhaité","rsvp.budget":"Budget par nuit","rsvp.passport":"Passeport / visa","rsvp.choose":"Choisir","rsvp.yesSimple":"Oui","rsvp.noSimple":"Non","rsvp.ready":"Tout est prêt","rsvp.inProgress":"En cours","rsvp.needHelp":"J’ai besoin d’informations","rsvp.back":"RETOUR","rsvp.next":"CONTINUER","rsvp.submit":"ENVOYER MA RÉPONSE"
  },
  en:{
    "entry.kicker":"Marrakech · May 25—26, 2027","entry.open":"OPEN THE INVITATION",
    "cover.kicker":"WE ARE GETTING MARRIED","cover.place":"Marrakech","cover.date":"May 25 — 26, 2027",
    "photo.kicker":"THE WEDDING OF","photo.placeholder":"Original photo to be added",
    "countdown.title":"COUNTING DOWN","countdown.days":"DAYS","countdown.hours":"HOURS","countdown.minutes":"MINUTES","countdown.seconds":"SECONDS",
    "calendar.title":"May 2027","calendar.mo":"M","calendar.tu":"T","calendar.we":"W","calendar.th":"T","calendar.fr":"F","calendar.sa":"S","calendar.su":"S","calendar.note":"May 25 & 26 · Marrakech",
    "venue.kicker":"OUR RECEPTION VENUE","venue.title":"The Venue","venue.route":"GET DIRECTIONS",
    "program.kicker":"TWO DAYS · TWO WORLDS","program.title":"Schedule","program.roots":"ROOTS","program.brideHenna":"Bride’s henna","program.groomHenna":"Groom’s henna","program.arrival":"Guest arrival","program.families":"Family welcome","program.tuaregEvening":"Traditional Tuareg evening","program.dinner":"Dinner","program.music":"Tuareg music / guitar","program.tea":"Tea & pastries","program.celebration":"THE CELEBRATION","program.ceremony":"Ceremony","program.cocktail":"Welcome cocktail","program.seatedDinner":"Seated dinner","program.speeches":"Speeches","program.firstDance":"First dance","program.dj":"DJ & evening celebration","program.note":"Unconfirmed times will be added once they are finalized.",
    "dress.title":"Dress Code","dress.day1":"Traditional / elegant","dress.day2":"Elegant",
    "practical.kicker":"WEDDING DETAILS","practical.title":"Practical information","practical.accommodation":"Accommodation","practical.transport":"Transport","practical.arrival":"Arriving in Marrakech","practical.passport":"Passport / visa","practical.weather":"Weather","practical.currency":"Currency","practical.mobility":"Getting around","practical.parking":"Parking","practical.children":"Children","practical.photos":"Photos","practical.indoorOutdoor":"Indoor / outdoor ceremony","practical.pending":"Details coming soon.",
    "travel.kicker":"MARRAKECH NOTEBOOK","travel.title":"Extend the Journey","travel.discover":"Discover","travel.restaurants":"Restaurants","travel.cafes":"Cafés","travel.souks":"Souks & crafts","travel.hammams":"Hammams","travel.excursions":"Excursions","travel.clothing":"Traditional clothing","travel.pending":"Our selected addresses will be added here.",
    "story.kicker":"A FEW LINES","story.title":"Our Story","story.one":"Two paths.","story.two":"Roots that travel with us.","story.three":"And Marrakech, May 25 & 26, 2027.",
    "rsvp.kicker":"RESPONSE CARD","rsvp.question":"Will you be joining us?","rsvp.deadline":"Reply by","rsvp.step1":"Your response","rsvp.yes":"Yes, with pleasure","rsvp.no":"Sadly, no","rsvp.firstName":"First name","rsvp.lastName":"Last name","rsvp.step2":"Your attendance","rsvp.companion":"Guest / companion","rsvp.children":"Children","rsvp.transport":"Transport request / useful information","rsvp.step3":"Meals & preferences","rsvp.allergies":"Allergies","rsvp.diet":"Dietary preferences","rsvp.alcohol":"Alcohol","rsvp.traditional":"Traditional attire","rsvp.step4":"Stay","rsvp.lodging":"Accommodation requested","rsvp.budget":"Budget per night","rsvp.passport":"Passport / visa","rsvp.choose":"Choose","rsvp.yesSimple":"Yes","rsvp.noSimple":"No","rsvp.ready":"Everything is ready","rsvp.inProgress":"In progress","rsvp.needHelp":"I need information","rsvp.back":"BACK","rsvp.next":"CONTINUE","rsvp.submit":"SEND MY RSVP"
  },
  ar:{
    "entry.kicker":"مراكش · 25—26 مايو 2027","entry.open":"فتح الدعوة",
    "cover.kicker":"نحن نتزوّج","cover.place":"مراكش","cover.date":"25 — 26 مايو 2027",
    "photo.kicker":"زفاف","photo.placeholder":"ستُضاف الصورة الأصلية هنا",
    "countdown.title":"العدّ التنازلي","countdown.days":"أيام","countdown.hours":"ساعات","countdown.minutes":"دقائق","countdown.seconds":"ثوانٍ",
    "calendar.title":"مايو 2027","calendar.mo":"ن","calendar.tu":"ث","calendar.we":"ر","calendar.th":"خ","calendar.fr":"ج","calendar.sa":"س","calendar.su":"ح","calendar.note":"25 و26 مايو · مراكش",
    "venue.kicker":"مكان حفلنا","venue.title":"المكان","venue.route":"عرض الطريق",
    "program.kicker":"يومان · عالمان","program.title":"البرنامج","program.roots":"الجذور","program.brideHenna":"حناء العروس","program.groomHenna":"حناء العريس","program.arrival":"وصول الضيوف","program.families":"استقبال العائلتين","program.tuaregEvening":"أمسية طوارقية تقليدية","program.dinner":"العشاء","program.music":"موسيقى وغيتار طوارقي","program.tea":"الشاي والحلويات","program.celebration":"الاحتفال","program.ceremony":"المراسم","program.cocktail":"استقبال وكوكتيل","program.seatedDinner":"عشاء على الطاولة","program.speeches":"الكلمات","program.firstDance":"الرقصة الأولى","program.dj":"دي جي وسهرة","program.note":"ستُضاف المواعيد غير المؤكدة فور اعتمادها.",
    "dress.title":"قواعد اللباس","dress.day1":"تقليدي / أنيق","dress.day2":"أنيق",
    "practical.kicker":"تفاصيل الزفاف","practical.title":"معلومات عملية","practical.accommodation":"الإقامة","practical.transport":"النقل","practical.arrival":"الوصول إلى مراكش","practical.passport":"جواز السفر / التأشيرة","practical.weather":"الطقس","practical.currency":"العملة","practical.mobility":"التنقل","practical.parking":"موقف السيارات","practical.children":"الأطفال","practical.photos":"الصور","practical.indoorOutdoor":"المراسم داخلية / خارجية","practical.pending":"ستُضاف المعلومات لاحقاً.",
    "travel.kicker":"دفتر مراكش","travel.title":"أطيلوا الرحلة","travel.discover":"أماكن لاكتشافها","travel.restaurants":"مطاعم","travel.cafes":"مقاهٍ","travel.souks":"الأسواق والحرف","travel.hammams":"حمّامات","travel.excursions":"رحلات","travel.clothing":"ملابس تقليدية","travel.pending":"سنضيف هنا عناويننا المختارة.",
    "story.kicker":"بضع كلمات","story.title":"قصتنا","story.one":"طريقان.","story.two":"جذور ترافقنا أينما ذهبنا.","story.three":"ثم مراكش، في 25 و26 مايو 2027.",
    "rsvp.kicker":"بطاقة تأكيد الحضور","rsvp.question":"هل ستكونون معنا؟","rsvp.deadline":"آخر موعد","rsvp.step1":"إجابتكم","rsvp.yes":"نعم، بكل سرور","rsvp.no":"للأسف، لا","rsvp.firstName":"الاسم الأول","rsvp.lastName":"اسم العائلة","rsvp.step2":"تفاصيل الحضور","rsvp.companion":"المرافق","rsvp.children":"الأطفال","rsvp.transport":"النقل المطلوب / معلومات مفيدة","rsvp.step3":"الطعام والتفضيلات","rsvp.allergies":"الحساسيات","rsvp.diet":"التفضيلات الغذائية","rsvp.alcohol":"الكحول","rsvp.traditional":"اللباس التقليدي","rsvp.step4":"الإقامة","rsvp.lodging":"هل ترغبون في مساعدة بخصوص الإقامة؟","rsvp.budget":"الميزانية لكل ليلة","rsvp.passport":"جواز السفر / التأشيرة","rsvp.choose":"اختيار","rsvp.yesSimple":"نعم","rsvp.noSimple":"لا","rsvp.ready":"كل شيء جاهز","rsvp.inProgress":"قيد الإعداد","rsvp.needHelp":"أحتاج إلى معلومات","rsvp.back":"رجوع","rsvp.next":"متابعة","rsvp.submit":"إرسال الرد"
  }
};